### ISSUE TITLE
Distrubuted runner: ModuleNotFoundError: No module named 'tensorflow'

### ISSUE THREAD

**Issue by FlowAlpha** [Sanford-Lab/satellite_cnns#6]
ModuleNotFoundError: No module named 'tensorflow' [while running '✍🏽 Serialize-ptransform-64']

      Worker ID: beamapp-root-0702040135-0-07012101-vfbh-harness-wgkt,

      Root cause: Traceback (most recent call last):
      File "apache_beam/runners/common.py", line 1418, in apache_beam.runners.common.DoFnRunner.process
      File "apache_beam/runners/common.py", line 625, in apache_beam.runners.common.SimpleInvoker.invoke_process
      File "[/usr/local/lib/python3.10/dist-packages/ap](https://colab.research.google.com/drive/1H8xB2p8iHsz5FIuaMxBaUN2KzaGEsqzp?authuser=1#)ache_beam/transforms/core.py", line -1, in <lambda>
      File "[/content/satellite_cnns/create_dataset.py](https://colab.research.google.com/drive/1H8xB2p8iHsz5FIuaMxBaUN2KzaGEsqzp?authuser=1#)", line 52, in serialize_tensorflow
      ModuleNotFoundError: No module named 'tensorflow'

`serialize_tensorflow` seems to be failing in DataFlow pipeline. See [failed jobs](https://console.cloud.google.com/dataflow/jobs?project=ls-test-3-24&authuser=0) in GC console. Probably import error
- Possible solution: packaging things better
- Possible solution: handing tensorflow SDK to Dataflow with our benin-data package; this would probably fix error, but still unsure of why tensorflow can't be found

TODO (@FlowAlpha): test pipeline output locally, though no serialization errors when running local pipeline.

**Comment by FlowAlpha** [comment]
Problem is Apache-Beam SDK 2.48.0 doesn't include tensorflow:

See [2.48.0 setup.py ](https://raw.githubusercontent.com/apache/beam/v2.48.0/sdks/python/setup.py)

### Solution if we want to switch back to tensorflow:
**Use custom SDK container or the pre-built [GC Tensorflow SDK](https://cloud.google.com/vertex-ai/docs/training/pre-built-containers#tensorflow) would probably work too.**
